from typing import Protocol

from app.domain.models.tmdb_user import TmdbUser


class TmdbUserRepoPort(Protocol):
    async def get_user_by_id(self, user_id: int) -> TmdbUser | None: ...

    async def get_user_by_name(self, name: str) -> TmdbUser | None: ...

    async def get_user_by_access_token(self, access_token: str) -> TmdbUser | None: ...

    async def get_active_users(self) -> list[TmdbUser]: ...

    async def create_user(self, user: TmdbUser) -> TmdbUser: ...

    async def update_user(self, user: TmdbUser) -> TmdbUser | None: ...

    async def delete_user(self, user: TmdbUser) -> TmdbUser | None: ...
