from typing import Protocol, List, Optional
from app.domain.models.plexUser import PlexUser
class PlexUserRepoPort(Protocol):
    async def get_active_users(self) -> List[PlexUser]:
        ...
    async def get_user_by_id(self, user_id: int) -> Optional[PlexUser]:
        ...
    async def getByName(self, name: str) -> Optional[PlexUser]:
        ...
    async def create(self, user: PlexUser) -> PlexUser:
        ...
    async def update(self, user: PlexUser) -> PlexUser:
        ...

