from typing import Protocol, List, Optional
from app.domain.models.plexUser import PlexUser
class PlexUserRepoPort(Protocol):
    async def get_active_users(self) -> List[PlexUser]:
        ...
    async def get_user_by_id(self, user_id: int) -> Optional[PlexUser]:
        ...
    async def get_user_by_name(self, name: str) -> Optional[PlexUser]:
        ...
    async def get_user_by_plex_token(self, plex_token: str) -> Optional[PlexUser]:
        ...
    async def create_user(self, user: PlexUser) -> PlexUser:
        ...
    async def update_user(self, user: PlexUser) -> Optional[PlexUser]:
        ...
    async def delete_user(self, user: PlexUser) -> Optional[PlexUser]:
        ...

